name: ServerStats
main: me.diced.serverstats.bukkit.BukkitServerStats
version: ${version}
api-version: 1.13
description: Visualize your Minecraft server statistics in realtime
authors: [dicedtomato]
website: https://serverstats.diced.me

commands:
  stats:
    description: Manage Server Stats