name: Build ServerStats
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Build
        run: ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: builds